### ISSUE TITLE
Don't pollute $HOME by default

### ISSUE THREAD

**Issue by mvdan** [rogpeppe/gohack#5] opened 2018-08-07 21:30 UTC
I know the purpose of `~/gohack`, but I'm not a big fan of tools that add stuff to my home directory by default.

Perhaps we could use `$GOPATH/hack` or something else instead. Don't have a clear answer to this one.

**Comment by rogpeppe** [comment] 2018-08-08 09:16
So, it's by design that it always pulls stuff to some consistent directory, rather than local to the module you're working on. `$GOPATH` doesn't seem quite right as we don't want GO111MODULE=off to kick in when you're working in one of the gohacked modules. We could make the command refuse to work if there's no GOHACK env var set, but that doesn't seem that great either. More suggestions welcome.

**Comment by rogpeppe** [comment] 2018-08-18 09:28
I think it's probably OK as is for now, barring some other good idea, so I'll close the issue.

**Closed by rogpeppe** 2018-08-18 09:28 UTC
Labels: needs decision
